### ISSUE TITLE
NickelClock Not Initializing

### ISSUE THREAD

**Issue by liuwhoo** [shermp/NickelClock#13]
After following install instructions, time does not appear in the header. The settings.ini file also does not show in the specified location. A log file was created on my Kobo and said the following:

Aug 15 19:56:57 syslogd started: BusyBox v1.22.0.kobo
Aug 15 19:56:58 nickel: (     0.554 @ 0x174f710) FT_New_Face failed with index 0 : 0 
Aug 15 19:56:58 nickel: (     1.037 @ 0x174f710) FT_New_Face failed with index 0 : 0 
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) initializing 'NickelClock' (version: v0.2.0)
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) ... desc: Set an always displayed clock when reading
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) creating failsafe
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) ... failsafe: info: allocating memory
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) ... failsafe: info: finding filenames
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) ... failsafe: info: ensuring own lib remains in memory even if it is dlclosed after being loaded with a dlopen
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) ... failsafe: info: renaming /usr/local/Kobo/imageformats/libnickelclock.so to /usr/local/Kobo/imageformats/libnickelclock.so.failsafe
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) checking config
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) checking for uninstall !flag '/mnt/onboard/.adds/nickelclock/uninstall'
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) loading libraries
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) resolving symbols
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) info: nh_dlsym: loading symbol '_ZN9TimeLabelC1EP7QWidget' from RTLD_DEFAULT to 0x6f556260 (desc: TimeLabel::TimeLabel())
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) ... fatal: could not load symbol: /usr/local/Kobo/imageformats/libnickelclock.so: undefined symbol: _ZN9TimeLabelC1EP7QWidget
Aug 15 19:56:59 nickel: (NickelClock) (NickelHook) fatal error

I tried using both the 3.1 version and the 2.0 version, both of which returned identical errors on the log. Anything I can do to get it working?

**Comment by shermp** [comment]
Hi, what firmware version are you running?

If it is an older firmware version, it might be too old.

**Comment by liuwhoo** [comment]
4.21.15023, which seems pretty old. Didn't realize that it was not auto-updating. I will try to force an update. Thank you!!

**Comment by liuwhoo** [comment]
Worked with update to 4.37! Thanks so much!

**Comment by shermp** [comment]
No worries. When I get some time, I'll try and discover which version is the minimum FW version (it's probably 4.23).
