### ISSUE TITLE
Nickel Clock not displaying

### ISSUE THREAD

**Issue by garywalker-WA** [shermp/NickelClock#15]
Installed following the instructions, device restareted as expected, launched a book, not seeing the clock, updated the ini file to put it to the bottom right, still nothing. Kobo Libra2 FW 4.38.21908

Not sure where to find log files. Didn't see one in the .adds folder.

**Comment by shermp** [comment]
Just to confirm, you have not disabled your header/footer on your Kobo have you?

**Comment by garywalker-WA** [comment]
It was when i installed. But i turned them both on and it still wasn’t showing. Should i uninstall and turn them on and reinstall?Sent from my iPhoneOn Jan 13, 2024, at 19:54, Sherman Perry ***@***.***> wrote:﻿
Just to confirm, you have not disabled your header/footer on your Kobo have you?

**Comment by shermp** [comment]
Just to confirm, you installed it by copying the `KoboRoot.tgz` file to the `.kobo` directory, and it rebooted itself after you ejected the kobo from your computer?

**Comment by shermp** [comment]
If it really did install correctly, is there a log file called `NickelHook.log` on the Kobo drive?

**Comment by garywalker-WA** [comment]
Correct. Sent from my iPhoneOn Jan 13, 2024, at 20:11, Sherman Perry ***@***.***> wrote:﻿
Just to confirm, you installed it by copying the KoboRoot.tgz file to the .kobo directory, and it rebooted itself after you ejected the kobo from your computer?

**Comment by garywalker-WA** [comment]
no log file that I can find on the volume.

**Comment by shermp** [comment]
I have created a new version which adds a `Debug` setting. You can download it from https://github.com/shermp/NickelClock/actions/runs/7517249258/artifacts/1167898461

Install the new version like before. Once your Kobo has restarted, edit the settings and add (or modify) the following setting to the `[General]` group:

```
Debug=true
```

Then open a book. Once you have opened a book, you should find a log file like `NickelClock_xxx-xx-xx_xx-xx-xx.log` when you reconnect your Libra2 to USB. Please post that log here.

**Comment by garywalker-WA** [comment]
OK, for some reason, with no updates other than the Debug=true, I saw the clock in nmy header and after enabling the battery, and moving the clock to the footer, I still see it. I'm going to put it down to me being tired and doing something, thank you for walking me through it. We can close now.
[NickelClock_124-00-14_05-13-52.log](https://github.com/shermp/NickelClock/files/13931623/NickelClock_124-00-14_05-13-52.log)
