### ISSUE TITLE
Bootloop Clara bw

### ISSUE THREAD

**Issue by PeterJT** [shermp/NickelClock#16]
On Reddit an early recipient of the Clara BW has reported that nickelclock and nickelmenu cause bootloops.

See https://www.reddit.com/r/kobo/comments/1cam89j/kobo_clara_bw_first_thoughts/

**Comment by PeterJT** [comment]
Thanks. I thought I'd open an issue as the best way to reach you

**Comment by shermp** [comment]
Note: this was a user error. NickelClock appears to be safe to use.
