### ISSUE TITLE
Battery percentage always 100% on Kobo Clara BW

### ISSUE THREAD

**Issue by metronidazole** [shermp/NickelClock#17]
First time using this so I'm not sure if this is specific to the Kobo Clara BW. I've installed this mod and I enabled the battery indicator but it always says 100%. This is with and without any usb cable connected. The clock works fine though.

Here is my config:
```
[General]
Margin=Auto

[Battery]
BatteryType=Level
Enabled=true
LevelTemplate=%1%
Placement=Footer
Position=Right

[Clock]
Enabled=true
Placement=Footer
Position=Left
```

**Comment by shermp** [comment]
Hi, thanks for the report. I believe Kobo are using different power management hardware from what I've previously known about. A Libra Colour user has confirmed there's changes.

I'll look into fixing this later today or tomorrow. I may have an alternative method that is more hardware agnostic.

**Comment by shermp** [comment]
I've pushed a potential fix. Can you please try the following version?

https://github.com/shermp/NickelClock/actions/runs/8936925578/artifacts/1470101681
