### ISSUE TITLE
Can't change positioning?

### ISSUE THREAD

**Issue by Dr-Evazan** [shermp/NickelClock#8]
Hi there - I've read through the faq and edited settings.ini to move the clock to the left (position=left), but something keeps reverting the settings.ini to show -

[General]
hor_margin=auto
placement=header
position=right

I guess it's reverting after a reboot. I have a Libra H20. 

Thanks for the hard work. :)

**Comment by sjb217** [comment]
Confirmed.
The settings file reverts to original after I disconnect my Libra 2 from my PC.

**Comment by Cempres** [comment]
This is still a persistent issue on my Sage. can't seem to fix the reverting of the .ini file to it's default values even when i put it into Read-only @shermp any fix for this or tips?

**Comment by Cempres** [comment]
Quick update for anyone sturggling, I've formated my Kobo Sage for various reasons, re-installed Nickelmenu, set it up, and re-installed NickelClock, but set the config file on my PC and then copied it over onto my kobo, and it seems to have worked now, hope this helps!

**Comment by Dr-Evazan** [comment]
Lo and behold, Cempres' fix worked. No thanks to the developer, of course, who couldn't care less about this.

**Comment by shermp** [comment]
Hi, my apologies for missing this, it must have slipped through the cracks.

I'm, not sure what may have been the cause of this, it could potentially be an issue of text editors changing the line endings or something.
