### ISSUE TITLE
Installation instructions incorrect?

### ISSUE THREAD

**Issue by sach160** [shermp/NickelClock#9]
Hi, I've tried to install this on my Libra 2, but it doesn't work - are the installation instructions accurate? When I download NickelClock-<version>.zip the file is Koboroot.tar not Koboroot.tgz. Anyway I extract it, which gives a folder  called "Koboroot". I have tried copying this to .kobo folder, unplugging and rebooting (doesn't reboot automatically) and nothing happens. Tried copying just the contents too. Am I missing something?

**Comment by shermp** [comment]
Are you on Mac? If so, Mac OS "helpfully" extracts the file for you, which is not what is desired in this case.

To stop this from happening, in Safari, go `Preferences` > `General` and uncheck `Open safe files after downloading`.

Alternatively, use a different browser like Chrome or Firefox.

**Comment by sach160** [comment]
Thank you - in my case it was my unarchiver program, automatically opening sub-archives so I never saw the tgz file. Got it working now - fantastic addition. Thank you so much!

**Comment by shermp** [comment]
You're welcome. Glad you got it sorted.
